lumirlumir/lumirlumir:
  - source: ./.github/sync-client.yml
    dest: ./clients/npm-clang-format-node.yml
  # ./.github/workflows
  - source: ./.github/workflows/ci.yml
    dest: ./configs/.github/workflows/ci.yml
  - source: ./.github/workflows/publish.yml
    dest: ./configs/.github/workflows/publish.yml
  - source: ./.github/workflows/pull-request.yml
    dest: ./configs/.github/workflows/pull-request.yml
  - source: ./.github/workflows/release.yml
    dest: ./configs/.github/workflows/release.yml
  - source: ./.github/workflows/sync-client.yml
    dest: ./configs/.github/workflows/sync-client.yml
  - source: ./.github/workflows/version-monorepo.yml
    dest: ./configs/.github/workflows/version-monorepo.yml
  # ./.github
  - source: ./.github/CODEOWNERS
    dest: ./configs/.github/CODEOWNERS
  - source: ./.github/dependabot.yml
    dest: ./configs/.github/dependabot.yml
  - source: ./.github/release.yml
    dest: ./configs/.github/release.yml
  # ./.husky
  - source: ./.husky/pre-commit
    dest: ./configs/.husky/pre-commit
  # ./.vscode
  - source: ./.vscode/extensions.json
    dest: ./configs/.vscode/extensions.json
  - source: ./.vscode/settings.json
    dest: ./configs/.vscode/settings.json
  # ./scripts
  - source: ./scripts/cp.js
    dest: ./configs/scripts/cp.js
  - source: ./scripts/vercel-ignore-command.js
    dest: ./configs/scripts/vercel-ignore-command.js
  - source: ./scripts/version.js
    dest: ./configs/scripts/version.js
  # ./
  - source: ./.editorconfig
    dest: ./configs/.editorconfig
  - source: ./.gitattributes
    dest: ./configs/.gitattributes
  - source: ./.gitignore
    dest: ./configs/.gitignore
  - source: ./.markdownlint.json
    dest: ./configs/.markdownlint.json
  - source: ./.markdownlintignore
    dest: ./configs/.markdownlintignore
  - source: ./.nvmrc
    dest: ./configs/.nvmrc
  - source: ./.prettierignore
    dest: ./configs/.prettierignore
  - source: ./LICENSE.md
    dest: ./configs/LICENSE.md
  - source: ./VScode.code-workspace
    dest: ./configs/VScode.code-workspace
  - source: ./eslint.config.js
    dest: ./configs/eslint.config.js
  - source: ./lint-staged.config.js
    dest: ./configs/lint-staged.config.js
  - source: ./prettier.config.js
    dest: ./configs/prettier.config.js
  - source: ./tsconfig.base.json
    dest: ./configs/tsconfig.base.json
