name: labeler

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  labeler:
    runs-on: ubuntu-latest

    steps:
      - name: Labeler
        if: github.event.action == 'opened' || github.event.changes.title
        uses: jimschubert/labeler-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
